server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/aisummarizer
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#Flyway (disabled using ddl-auto=update instead)
spring.flyway.enabled=false

## Redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

#  Cache
spring.cache.type=simple

# ?? Ollama ???????????????????????????????????????????????????????????
ai.url=http://localhost:11434/api/generate
ai.model=llama3.2

app.jwt.secret=jhasdfgajhdsbvuyertyuweyruwteyrtrtueytrwetruywteruwteruwetruwtruyetruwuyrwettyryt
app.jwt.expiry-ms=86400000
